[server]
headless = true
enableCORS = true
enableXsrfProtection = true
maxUploadSize = 200
port = 8501
address = "localhost"

[browser]
gatherUsageStats = false

[theme]
base = "dark"
primaryColor = "#2E8B57"
